# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HTMLTableExporterDialog
                                 A QGIS plugin
 Exports a table as an HTML table with photos which can later be converted into a Word document.  Perfect for organising site visit photos.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-02-09
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Lutra Consulting
        email                : info@lutraconsulting.co.uk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'html_table_exporter_dialog_base.ui'))


class HTMLTableExporterDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, iface, parent=None):
        self.iface = iface
        """Constructor."""
        super(HTMLTableExporterDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        # Populate layers combo
        for layer in self.iface.mapCanvas().layers():
            if layer.type() == 0:
                # It's a vector layer
                self.tableComboBox.addItem(layer.name())


